{
    'name': 'Kitchen Display Pro',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale/Restaurant',
    'sequence': 1,
    'summary': 'Professional Kitchen Display System for Restaurants & Food Service',
    'description': """
Transform your kitchen operations with a comprehensive digital display system designed for modern restaurants and food service businesses.
    """,
    'author': 'Azad Karipody Hamza - Digicyfr Polska',
    'maintainer': 'Digicyfr Polska',
    'support': 'info@digicyfr.com',
    'license': 'OPL-1',
    'price': 59.00,
    'currency': 'EUR',
    'images': [
        'static/description/icon.png',
        'static/description/screenshot_01.png',
        'static/description/screenshot_02.png',
        'static/description/screenshot_03.png',
        'static/description/screenshot_04.png',
        'static/description/screenshot_05.png',
    ],
    'depends': [
        'base',
        'point_of_sale',
        'pos_restaurant',
        'web',
        'mail',
        'bus',
        'hr',
        'stock',
        'product',
        'sale',
    ],
    'data': [
        'security/kitchen_display_security.xml',
        'security/ir.model.access.csv',
        'data/kitchen_display_data.xml',
        'views/product_views.xml',
        'views/kitchen_display_views.xml',
        'views/kitchen_order_views.xml',
        'views/menu_views.xml',
        'views/kitchen_board_custom.xml',
        'templates/kitchen_display_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'kitchen_display/static/src/css/kitchen_display.css',
            'kitchen_display/static/src/js/kitchen_display.js',
            'kitchen_display/static/src/js/kitchen_board.js',
            'kitchen_display/static/src/js/kitchen_kanban_controller.js',
        ],
    },
    'demo': [
        'demo/kitchen_display_demo.xml',
    ],
    'external_dependencies': {
        'python': [],
        'bin': [],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'bootstrap': True,
    'cloc_exclude': [
        'static/src/lib/**/*',
        'static/description/**/*',
    ],
    'development_status': 'Production/Stable',
    'maintainers': ['azad_hamza'],
}